version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '10:00'
    timezone: Asia/Calcutta
  open-pull-requests-limit: 10
  assignees: 
    - "th3c0d3br34ker"
